FROM ruby:2.6.5-stretch
COPY . /application
WORKDIR /application
VOLUME /bundle

EXPOSE 3000

ENV GEM_HOME /bundle
ENV BUNDLE_PATH /bundle
ENV BUNDLE_BIN_PATH /bundle/ruby/2.6.0/bin
ENV PATH=$BUNDLE_BIN_PATH:$PATH

ENV RAILS_ENV production
ENV DATABASE_HOST=192.168.33.11
ENV DATABASE_PORT=3306
ENV RAILS_MYSQL_TEST_APP_DATABASE_USERNAME=root
ENV RAILS_MYSQL_TEST_APP_DATABASE_PASSWORD=a
ENV REDIS_URL=redis://172.17.0.1:6379/1

RUN ln -s /bundle/vendor vendor

# ENTRYPOINT bundle exec rails server

# ENTRYPOINT [ "/bin/bash" ]
