#!/usr/bin/env bash

DATABASE_HOST="192.168.33.11"
DATABASE_PORT="3306"

bundle install --deployment --without development test
bundle exec rails db:migrate
bundle exec rails server --binding 0.0.0.0 -p 3000
